# Site settings
title: Tracedo
email: hello@tracedo.com
url: https://www.tracedo.com
copyright: Tracedo s.r.o.
owner: Tracedo s.r.o.
telephone: +420 777 211 754
baseurl: /tracedo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tracedo

# Postal address (add as many lines as necessary)
address:
  - line: Tracedo s.r.o.
  - line: U Špejcharu 409
  - line: 252 67 Tuchoměřice

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# Collections
collections:
    modules:
        output: true
    features:
        output: true
    benefits:
        output: true

# Exclude the following files/directories from being converted
exclude: ['.gitignore', 'CHANGELOG.md', 'Gemfile', 'Gemfile.lock', 'LICENSE.md', 'README.md', 'npm*', 'package.json']

gems:
  - jekyll-assets

# Assets
sass:
  sass_dir: _scss
  #style: compressed


# Assets Pipeline
assets:
  prefix: "/assets"
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/bower