# Site settings
title: Tracedo - online sledování přeprav
name: Tracedo
email: hello@tracedo.com
url: https://www.tracedo.com
copyright: Tracedo s.r.o.
owner: Tracedo s.r.o.
telephone: +420 777 211 754
baseurl: /

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tracedo

# Postal address (add as many lines as necessary)
address:
  - line: Tracedo s.r.o.
  - line: Dalimilova 579/5
  - line: 130 00 Praha 3

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# Collections
collections:
    modules:
        output: true
    features:
        output: true
    benefits:
        output: true
    customers:
        output: true
    tour:
        output: true

# Exclude the following files/directories from being converted
exclude: ['.gitignore', 'CHANGELOG.md', 'Gemfile', 'Gemfile.lock', 'LICENSE.md', 'README.md', 'npm*', 'package.json', 'node_modules', 'bower.json']

gems:
  - jekyll-assets

# Assets
sass:
  sass_dir: _scss

# Assets Pipeline
assets:
  prefix: "/assets"
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/bower